import { TileData } from '../types/board';
import { GAME_CONFIG } from '../constants/config';

export const PROTOTYPE_TILES: TileData[] = [
  {
    id: 0,
    name: 'START / CENTRAL RESERVE',
    gujaratiName: 'Shree Ganesh Gateway',
    type: 'START',
    position: 0,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#15803d',
    description: 'Collect ₹2,000 salary from NAVO BANK every time you pass or land here.',
    iconFrame: 14  // 3D Green START Arrow
  },
  {
    id: 1,
    name: 'Surat Diamond Market',
    gujaratiName: 'Diamond & Silk Exchange',
    type: 'PROPERTY',
    position: 1,
    price: 1200,
    baseRent: 150,
    category: 'DIAMOND',
    color: GAME_CONFIG.CATEGORY_COLORS.DIAMOND,
    description: 'World-renowned diamond cutting, polishing, and trading market.',
    iconFrame: 2   // Sparkling 3D Diamond
  },
  {
    id: 2,
    name: 'Navo Bank Central Vault',
    gujaratiName: 'Central Reserve Clearing',
    type: 'BANK',
    position: 2,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#eab308',
    description: 'Central economy reserve. Collect ₹500 trade dividend.',
    iconFrame: 12  // 3D Golden Bank Vault
  },
  {
    id: 3,
    name: 'Ahmedabad Textile Mill',
    gujaratiName: 'Sabarmati Cotton Hub',
    type: 'PROPERTY',
    position: 3,
    price: 1500,
    baseRent: 200,
    category: 'TEXTILE',
    color: GAME_CONFIG.CATEGORY_COLORS.TEXTILE,
    description: 'The historic Manchester of the East textile and fabric mill.',
    iconFrame: 1   // Brick Cotton Mill with chimney
  },
  {
    id: 4,
    name: 'Gujarat Commercial Tax',
    gujaratiName: 'State Tollway & Customs',
    type: 'TAX',
    position: 4,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#dc2626',
    description: 'State commercial logistics duty. Pay ₹800 to NAVO BANK.',
    iconFrame: 13  // 3D Boom Barrier Gate with Rupee coin
  },
  {
    id: 5,
    name: 'Vadodara Palace Grounds',
    gujaratiName: 'Laxmi Vilas Royal Estate',
    type: 'PROPERTY',
    position: 5,
    price: 2000,
    baseRent: 250,
    category: 'HERITAGE',
    color: GAME_CONFIG.CATEGORY_COLORS.HERITAGE,
    description: 'Magnificent Gaekwad royal palace grounds and cultural estate.',
    iconFrame: 3   // Grand Laxmi Vilas Royal Palace
  },
  {
    id: 6,
    name: 'Gujarat Samachar Press',
    gujaratiName: 'Commercial News Bulletin',
    type: 'EVENT',
    position: 6,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#8b5cf6',
    description: 'Market bulletin! Draw an opportunistic business card.',
    iconFrame: 15  // 3D Festive Golden Gift Box
  },
  {
    id: 7,
    name: 'Bhavnagar Maritime Port',
    gujaratiName: 'Alang Ship Cargo Yard',
    type: 'PROPERTY',
    position: 7,
    price: 2200,
    baseRent: 300,
    category: 'PORT',
    color: GAME_CONFIG.CATEGORY_COLORS.PORT,
    description: 'Key coastal shipping maritime terminal and international cargo port.',
    iconFrame: 8   // Modern container cargo ship & harbour crane
  },
  {
    id: 8,
    name: 'Statue of Unity Oasis',
    gujaratiName: 'Kevadia Ekta Sanctuary',
    type: 'SPECIAL',
    position: 8,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#0284c7',
    description: 'The world\'s tallest statue stands watch. Rest and skip penalty.',
    iconFrame: 0   // 182m Statue of Unity miniature
  },
  {
    id: 9,
    name: 'Rajkot Machine Works',
    gujaratiName: 'Precision Engineering Hub',
    type: 'PROPERTY',
    position: 9,
    price: 2500,
    baseRent: 350,
    category: 'INDUSTRY',
    color: GAME_CONFIG.CATEGORY_COLORS.INDUSTRY,
    description: 'Industrial casting, foundry machinery, and diesel engine capital.',
    iconFrame: 11  // Heavy bronze precision gear
  },
  {
    id: 10,
    name: 'Navo Bank Treasury',
    gujaratiName: 'Central Audit Branch',
    type: 'BANK',
    position: 10,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#eab308',
    description: 'Annual business deposit audit. Collect ₹400 interest.',
    iconFrame: 12  // 3D Golden Bank Vault
  },
  {
    id: 11,
    name: 'Jamnagar Brass Foundry',
    gujaratiName: 'Metal & Refining City',
    type: 'PROPERTY',
    position: 11,
    price: 2800,
    baseRent: 400,
    category: 'INDUSTRY',
    color: GAME_CONFIG.CATEGORY_COLORS.INDUSTRY,
    description: 'Premier brass component parts and petroleum refining capital.',
    iconFrame: 10  // Heavy refinery dome & brass foundry towers
  },
  {
    id: 12,
    name: 'Highway Toll & Customs',
    gujaratiName: 'Freight Logistics Duty',
    type: 'TAX',
    position: 12,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#dc2626',
    description: 'State freight transit permit. Pay ₹600 to NAVO BANK.',
    iconFrame: 13  // 3D Boom Barrier Gate
  },
  {
    id: 13,
    name: 'Gandhinagar GIFT City',
    gujaratiName: 'FinTech International Tower',
    type: 'PROPERTY',
    position: 13,
    price: 3200,
    baseRent: 450,
    category: 'TECH',
    color: GAME_CONFIG.CATEGORY_COLORS.TECH,
    description: 'GIFT International financial services, banking, & high-tech centre.',
    iconFrame: 7   // Modern blue glass skyscraper towers
  },
  {
    id: 14,
    name: 'Vyapar Mahotsav Expo',
    gujaratiName: 'Gujarat Trade Fair Gala',
    type: 'EVENT',
    position: 14,
    price: 0,
    baseRent: 0,
    category: 'SPECIAL',
    color: '#ec4899',
    description: 'Grand Gujarat business exhibition! Draw a trade bonus card.',
    iconFrame: 15  // 3D Festive Golden Gift Box
  },
  {
    id: 15,
    name: 'Dwarka Coastal Sanctuary',
    gujaratiName: 'Pilgrim Heritage Port',
    type: 'PROPERTY',
    position: 15,
    price: 3600,
    baseRent: 500,
    category: 'HERITAGE',
    color: GAME_CONFIG.CATEGORY_COLORS.HERITAGE,
    description: 'Ancient sacred coastal pilgrim heritage precinct and temple port.',
    iconFrame: 9   // Sacred ancient coastal golden temple spire
  }
];
